name: pypi-stat-update
on:
  schedule:
    // every 30 minutes
    - cron: "*/30 * * * 1"
jobs:
    resources:
        name: Update resources
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v1

            - uses: actions/setup-node@v1

            - name: Fetch resources
              run: ./scripts/fetch-resources.sh

            - name: Update resources
              uses: test-room-7/action-update-file@v1
              with:
                  file-path: path/to/file
                  commit-msg: hello world
                  github-token: ${{ secrets.GITHUB_TOKEN }}
