# .github/workflows/scheduled-builds.yml
name: pypi-stat-update

on:
  schedule:
    # Runs "at minute 0 past every hour"
    - cron: '0 * * * *'
jobs:
  build:
    name: tests
    runs-on: ubuntu-latest
    steps:
      - name: test1
        run: ./tasks/test.sh