# .github/workflows/scheduled-builds.yml
name: pypi-stat-update

on:
  schedule:
    # Runs at UTC 9:30am
    - cron: '30 9 * * *'
jobs:
  build:
    name: tests2
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v1

        - uses: actions/setup-node@v1

        - name: run bash
          run: |
            git update-index --chmod=+x ./tasks/test.sh
            sh ./tasks/test.sh

        - name: update file
          uses: test-room-7/action-update-file@v1
          with:
            file-path: source/test/hello-world.log
            commit-msg: hello world
            github-token: ${{ secrets.GITHUB_TOKEN }}